# error handling works

    Code
      safe_stop()
    Output
      Foo is Dropped!
    Condition
      Error:
      ! Error!

